#!/bin/bash

HCIDEV=${1:-hci0}

. /etc/iot/network.conf

rfkill unblock all

mymac=$(hciconfig $HCIDEV | egrep -io "(([0-9a-f]{2}:){5}[0-9a-f]{2})")

case $mymac in
	$SENSOR_BT)
		cd $(dirname $0)/sensor_source
		exec ./service.sh
		;;
	$ROUTER_BT)
		cd $(dirname $0)/local_router
		exec ./service.sh
		;;
	$SERVER_BT)
		cd $(dirname $0)/remote_server
		exec ./service.sh
		;;
	*)
		echo "Unknown bluetooth adapter"
		exit 1
esac

